name: kpro
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pickle
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - xgboost
    - scikit-learn
    - scipy
    - maplotlib
